add size to album details
deluan/navidrome pull request #561
Opened 2020-10-10 21:58 UTC by jrwren

for #534

2020-10-10 21:58 UTC, jrwren commented
The album details part looks like this now:

![image](https://user-images.githubusercontent.com/106443/95665871-3ae7de80-0b22-11eb-9dcc-66ce18e2638f.png)

2020-10-11 15:32 UTC, deluan requested changes
Great job! Just some minor adjustments before merging.

2020-10-11 15:32 UTC, deluan commented on Makefile
> +	goose -dir db/migration create ${name}
Ops, thanks for this :)

2020-10-11 15:32 UTC, deluan commented on db/migration/20201010162350_add_album_size.go
> +	/*  IS A RESCAN NECESSARY TO UPDATE ALBUM TABLE WITH SIZES?
Yes, the rescan will be necessary, as the sizes will be collected during the scan process

2020-10-11 15:32 UTC, deluan commented on db/migration/20201010162350_add_album_size.go
> +	add size integer default 0 not null;
Maybe also add an index for `size`, so in the future we can implement a "sort by size" in the UI?

2020-10-11 15:32 UTC, deluan commented on ui/src/album/AlbumDetails.js
> +          · <SizeField record={record} source="size" />
You should add a `{' '}` between the two fields, as you can see from your screenshot that the `·` is too close to the Duration time

2020-10-11 15:32 UTC, deluan commented on persistence/album_repository.go
> +		Size          int
This line is not required and can be removed. This `refreshAlbum` struct is for extra columns that are needed for post-processing the query results, if the value for a field in the result set is one-to-one to the expected album value, you don't need to do anything else.

2020-10-11 15:49 UTC, deluan commented
It would also be great to add `size` to the album details, so they are available in the Album list view: https://github.com/deluan/navidrome/blob/e6d1e67297295ab061575e449872fc00cc5aab2d/ui/src/album/AlbumListView.js#L32-L43

2020-10-12 15:10 UTC, merged

2020-10-12 15:10 UTC, deluan commented
LGTM. Thanks!

2020-10-18 19:19 UTC, jrwren commented
any chance in getting a hacktoberfest-accepted label on this PR?

2020-10-18 20:32 UTC, deluan commented
Sure, I'll add the [topic to the project](https://hacktoberfest.digitalocean.com/hacktoberfest-update) and the label to the PR